title: A generic GitHub Pages Website
author: jo3rn
description: >
  This website showcases a minimal GitHub Pages website.
  The content is generic.
twitter_username: jo3rnsen # DO NOT include the @ character, or else the build will fail!
github_username:  jo3rn # DO NOT include the @ character, or else the build will fail!
